/**
 * Feature 15: Project ZIP Download
 * Download entire project as a ZIP file.
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export async function downloadProjectZip(
  files: Array<{ path: string; content: string }>,
  projectName: string
) {
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  // Add README if not present
  if (!files.some((f) => f.path === 'README.md')) {
    zip.file(
      'README.md',
      `# ${projectName}\n\nGenerated by Pablo IDE.\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
    );
  }
  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${projectName}.zip`);
}
