#!/usr/bin/env node
/**
 * build-kb.js — Pre-build script that reads all docs/knowledge/*.md files
 * and generates lib/domain-kb/staticKB.ts with a typed KB_FILES array.
 *
 * Run: node scripts/build-kb.js
 * Called automatically by prebuild / prebuild:worker npm scripts.
 */

const fs = require('fs');
const path = require('path');

const KB_DIR = path.resolve(__dirname, '..', 'docs', 'knowledge');
const OUT_FILE = path.resolve(__dirname, '..', 'lib', 'domain-kb', 'staticKB.ts');

// Read all .md files from the knowledge directory
const files = fs.readdirSync(KB_DIR)
  .filter(f => f.endsWith('.md') && f !== 'README.md')
  .sort();

console.log(`[build-kb] Found ${files.length} KB files in docs/knowledge/`);

const entries = files.map(filename => {
  const filePath = path.join(KB_DIR, filename);
  const content = fs.readFileSync(filePath, 'utf-8');
  // Extract ID from filename: "01-architecture-patterns.md" -> "01-architecture-patterns"
  const id = filename.replace(/\.md$/, '');
  return { id, filename, content };
});

// Escape backticks and ${} for template literal safety
function escapeForTemplateLiteral(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

// Generate the TypeScript file
const tsContent = `// AUTO-GENERATED by scripts/build-kb.js — DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}
// Source: docs/knowledge/*.md (${entries.length} files)

export interface KBFile {
  id: string;
  filename: string;
  content: string;
}

export const KB_FILES: KBFile[] = [
${entries.map(e => `  {
    id: '${e.id}',
    filename: '${e.filename}',
    content: \`${escapeForTemplateLiteral(e.content)}\`,
  }`).join(',\n')}
];
`;

// Ensure output directory exists
const outDir = path.dirname(OUT_FILE);
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

fs.writeFileSync(OUT_FILE, tsContent, 'utf-8');
console.log(`[build-kb] Generated ${OUT_FILE} (${entries.length} files, ${(tsContent.length / 1024).toFixed(1)}KB)`);
